// Code generated by rlpgen. DO NOT EDIT.

//go:build !norlpgen
// +build !norlpgen

package types

import (
	"io"

	"github.com/cryptoecc/WorldLand/rlp"
)

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.UncleHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Difficulty == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Difficulty.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Difficulty)
	}
	if obj.Number == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}

	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.MixDigest[:])
	w.WriteBytes(obj.Nonce[:])
	_tmp1 := obj.BaseFee != nil
	if _tmp1 {
		if obj.BaseFee == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.BaseFee.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BaseFee)
		}
	}
	_tmp2 := obj.Codeword != nil
	if _tmp2 {
		if obj.Codeword == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.Codeword)
		}
	}
	if obj.CodeLength != 0 {
		w.WriteUint64(obj.CodeLength)
	}
	_tmp3 := obj.VRFProof != nil
	if _tmp3 {
		if obj.VRFProof == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.VRFProof)
		}
	}
	_tmp4 := obj.VRFPublicKey != nil
	if _tmp4 {
		if obj.VRFPublicKey == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.VRFPublicKey)
		}
	}
	_tmp5 := obj.VRFSignature != nil
	if _tmp5 {
		if obj.VRFSignature == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.VRFSignature)
		}
	}
	_tmp6 := obj.SortitionThreshold != nil
	if _tmp6 {
		if obj.SortitionThreshold == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.SortitionThreshold.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.SortitionThreshold)
		}
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
