// Code generated by rlpgen. DO NOT EDIT.

//go:build !norlpgen
// +build !norlpgen

package types

import (
	"io"

	"github.com/cryptoecc/WorldLand/rlp"
)

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.UncleHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Difficulty == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Difficulty.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Difficulty)
	}
	if obj.Number == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}

	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.MixDigest[:])
	w.WriteBytes(obj.Nonce[:])
	// Optional fields form one trailing RLP sequence. If a later field is
	// present, every earlier optional position must be encoded, using the empty
	// value where necessary. The generated code predates the TPM tail fields,
	// so keep the propagation explicit here.
	_tmp10 := obj.TPMWorkSignature != nil
	_tmp9 := obj.TPMWorkPublicKey != nil || _tmp10
	_tmp8 := obj.TPMDID != nil || _tmp9
	_tmp7 := obj.EligibilityThreshold != nil || _tmp8
	_tmp6 := obj.VRFSignature != nil || _tmp7
	_tmp5 := obj.VRFPublicKey != nil || _tmp6
	_tmp4 := obj.VRFProof != nil || _tmp5
	_tmp3 := obj.CodeLength != 0 || _tmp4
	_tmp2 := obj.Codeword != nil || _tmp3
	_tmp1 := obj.BaseFee != nil || _tmp2
	if _tmp1 {
		if obj.BaseFee == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.BaseFee.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BaseFee)
		}
	}
	if _tmp2 {
		if obj.Codeword == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.Codeword)
		}
	}
	if _tmp3 {
		w.WriteUint64(obj.CodeLength)
	}
	if _tmp4 {
		if obj.VRFProof == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.VRFProof)
		}
	}
	if _tmp5 {
		if obj.VRFPublicKey == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.VRFPublicKey)
		}
	}
	if _tmp6 {
		if obj.VRFSignature == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.VRFSignature)
		}
	}
	if _tmp7 {
		if obj.EligibilityThreshold == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.EligibilityThreshold.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.EligibilityThreshold)
		}
	}
	if _tmp8 {
		if obj.TPMDID == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.TPMDID)
		}
	}
	if _tmp9 {
		if obj.TPMWorkPublicKey == nil {
			w.Write(rlp.EmptyString)
		} else {
			w.WriteBytes(obj.TPMWorkPublicKey)
		}
	}
	if _tmp10 {
		w.WriteBytes(obj.TPMWorkSignature)
	}
	w.ListEnd(_tmp0)
	return w.Flush()
}
