// Package tpmregistry implements the hashes signed by TPM registration validators.
//
//go:generate go run ./internal/solcgen
package tpmregistry

import (
	"errors"
	"math/big"

	"github.com/cryptoecc/WorldLand/common"
	"github.com/cryptoecc/WorldLand/crypto"
)

var (
	domainTypeHash     = crypto.Keccak256Hash([]byte("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"))
	enrollmentTypeHash = crypto.Keccak256Hash([]byte("Enrollment(bytes32 requestId,bytes32 did,address controller,bytes32 workKeyHash,bytes32 vrfKeyHash,bytes32 profileHash,bytes32 deviceNullifier,bytes32 policyDigest,bytes32 evidenceHash,uint64 validatorEpoch,uint64 deadline)"))
	nameHash           = crypto.Keccak256Hash([]byte("WorldLand TPM DID Registry"))
	versionHash        = crypto.Keccak256Hash([]byte("2"))
	didDomain          = crypto.Keccak256Hash([]byte("WorldLand TPM DID v1"))
)

// EnrollmentStatement is the EIP-712 statement approved by registration validators.
// PolicyDigest identifies the exact certificate roots, TPM profiles and evidence
// validation rules used for ValidatorEpoch.
type EnrollmentStatement struct {
	RequestID       common.Hash
	DID             common.Hash
	Controller      common.Address
	WorkKeyHash     common.Hash
	VRFKeyHash      common.Hash
	ProfileHash     common.Hash
	DeviceNullifier common.Hash
	PolicyDigest    common.Hash
	EvidenceHash    common.Hash
	ValidatorEpoch  uint64
	Deadline        uint64
}

// DeriveConsensusIdentity derives the chain-scoped TPM-bound consensus
// identity. The Solidity ABI retains the historical deriveDID name for storage
// and network compatibility.
func DeriveConsensusIdentity(chainID *big.Int, registry common.Address, deviceNullifier common.Hash) common.Hash {
	return crypto.Keccak256Hash(encodeWords(
		didDomain[:],
		chainID.Bytes(),
		registry[:],
		deviceNullifier[:],
	))
}

// DeriveDID is the legacy name retained for callers built against the first
// prototype. New code should use DeriveConsensusIdentity.
func DeriveDID(chainID *big.Int, registry common.Address, deviceNullifier common.Hash) common.Hash {
	return DeriveConsensusIdentity(chainID, registry, deviceNullifier)
}

// DeriveRequestID mirrors the request identifier generated by beginRegistration.
func DeriveRequestID(registry common.Address, chainID *big.Int, controller common.Address, nonce *big.Int) common.Hash {
	return crypto.Keccak256Hash(encodeWords(
		registry[:],
		chainID.Bytes(),
		controller[:],
		nonce.Bytes(),
	))
}

// StructHash returns the EIP-712 Enrollment struct hash stored in a request.
func (s EnrollmentStatement) StructHash() common.Hash {
	return crypto.Keccak256Hash(encodeWords(
		enrollmentTypeHash[:],
		s.RequestID[:],
		s.DID[:],
		s.Controller[:],
		s.WorkKeyHash[:],
		s.VRFKeyHash[:],
		s.ProfileHash[:],
		s.DeviceNullifier[:],
		s.PolicyDigest[:],
		s.EvidenceHash[:],
		new(big.Int).SetUint64(s.ValidatorEpoch).Bytes(),
		new(big.Int).SetUint64(s.Deadline).Bytes(),
	))
}

// DomainSeparator mirrors TPMDIDRegistry.domainSeparator.
func DomainSeparator(chainID *big.Int, registry common.Address) common.Hash {
	return crypto.Keccak256Hash(encodeWords(
		domainTypeHash[:],
		nameHash[:],
		versionHash[:],
		chainID.Bytes(),
		registry[:],
	))
}

// ApprovalDigest returns the EIP-712 digest validators sign.
func ApprovalDigest(chainID *big.Int, registry common.Address, statement EnrollmentStatement) common.Hash {
	domain := DomainSeparator(chainID, registry)
	statementHash := statement.StructHash()
	return crypto.Keccak256Hash([]byte{0x19, 0x01}, domain[:], statementHash[:])
}

// RecoverApprovalSigner recovers either a Go-style (v=0/1) or Ethereum-style
// (v=27/28) validator signature accepted by the registry contract.
func RecoverApprovalSigner(digest common.Hash, signature []byte) (common.Address, error) {
	if len(signature) != crypto.SignatureLength {
		return common.Address{}, errors.New("invalid approval signature length")
	}
	normalized := append([]byte(nil), signature...)
	if normalized[crypto.RecoveryIDOffset] >= 27 {
		normalized[crypto.RecoveryIDOffset] -= 27
	}
	pub, err := crypto.SigToPub(digest[:], normalized)
	if err != nil {
		return common.Address{}, err
	}
	return crypto.PubkeyToAddress(*pub), nil
}

func encodeWords(values ...[]byte) []byte {
	encoded := make([]byte, 32*len(values))
	for i, value := range values {
		if len(value) > 32 {
			panic("tpmregistry: ABI word exceeds 32 bytes")
		}
		copy(encoded[(i+1)*32-len(value):(i+1)*32], value)
	}
	return encoded
}
